db.items.find();
var bulk = db.items.initializeUnorderedBulkOp();
bulk;
bulk.insert({item: "mesa", valor: 5000, existencia: 2});
bulk.insert({item: "fuente", valor: 300, existencia: 10});
bulk.insert({item: "maseta", valor: 150, existencia: 16});
bulk.insert({item: "escoba", valor: 200, existencia: 5});
bulk.insert({item: "silla", valor: 600, existencia: 20});
db.items.find();
bulk;
bulk.find({});
bulk.execute();
bulk;
db.items.find();
var b = db.items.initializeOrderedBulkOp();
b;
b.find({item: "abc123"}).remove();
b.find({item: "caja", valor: 50}).remove();
b.find({item: "escoba"}).update({$inc: {existencia: 10}});
b.execute();
b;
db.items.find();

